apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  namespace: default
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: supriya/restaurant:latest   # ⚠️ Replace this with your real image (Docker Hub)
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
