apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
